services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /opt/ollama/models:/root/.ollama:Z
    environment:
      - OLLAMA_KEEP_ALIVE=-1