services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - models:/root/.ollama
    restart: always
    networks:
      - nana-net
  server-status:
    image: restartdk/glance-server-status:latest
    container_name: server-status
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys:/sys:ro
    ports:
      - "8080:8080"


volumes:
  data:
  models:
networks:
  nana-net:
    driver: bridge
