version: '3.8'

services:
  # Ollama AI service
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - homelab-network

  # Portainer Agent
  portainer-agent:
    image: portainer/agent:2.33.0
    networks:
      - homelab-network
    ports:
      - "9001:9001"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

volumes:
  ollama_data:
    driver: local

networks:
  homelab-network:
    driver: overlay
    attachable: true
