version: '3.8'

services:
  portainer-agent:
    image: portainer/agent:2.33.0
    networks:
      - agent_network
    ports:
      - "9001:9001"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

networks:
  agent_network:
    driver: overlay
    attachable: true
