name: homelab
services:
  caddy:
    container_name: caddy
    hostname: caddy
    image: restartdk/caddy-cloudflare:latest
    restart: unless-stopped
    networks:
      - caddynet
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - .env 
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:Z
      - ${CERTIFICATES_PATH}:/data:Z
      - ${CADDY_PATH}/config:/config:Z
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAIN=${DOMAIN}
      - GLANCE_PORT=${GLANCE_PORT}
      - KOMGA_PORT=${KOMGA_PORT}
      - JELLYFIN_PORT=${JELLYFIN_PORT}
      - JELLYSEERR_PORT=${JELLYSEERR_PORT}
      - SERVER_IP=${SERVER_IP}
      - COCKPIT_PORT=${COCKPIT_PORT}
    extra_hosts:
         - host.docker.internal:host-gateway
    
  tailscale:
      image: "tailscale/tailscale:latest"
      container_name: tailscale
      hostname: ${TAILSCALE_NAME}
      restart: unless-stopped
      network_mode: host
      env_file:
        - .env
      cap_add:
      - NET_ADMIN
      - SYS_MODULE
      environment:
        # location of the state directory of tailscale daemon - needs to be persisted between restarts
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
        - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=${LOCAL_ROUTES}
      volumes:
        - ${TAILSCALE_DATA_PATH}:/var/lib/tailscale:Z
        - /dev/net/tun:/dev/net/tun
      healthcheck:
        test: ["CMD-SHELL", "tailscale status --peers=false --json | grep -q 'Online.*true'"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    networks:
      - caddynet
    env_file:
      - .env 
    volumes:
      - ${GLANCE_PATH}/config:/app/config:Z
      - ${ASSETS_PATH}:/app/assets:Z
    ports:
      - 8080:${GLANCE_PORT}
    environment:
      - GLANCE_PORT=${GLANCE_PORT}
      - GLANCE_SECRET=${GLANCE_SECRET}
      - GLANCE_DANIEL_PASSWORD=${GLANCE_DANIEL_PASSWORD}
      - SERVER_URL=${SERVER_URL}

  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    networks:
      - caddynet
    env_file:
      - .env 
    volumes:
      - ${KOMGA_PATH}/config:/config:Z
      - ${BOOKS_PATH}:/data:Z
    ports:
      - 25600:${KOMGA_PORT}

  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: suwayomi
    restart: unless-stopped
    networks:
      - caddynet
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${MANGA_PATH}:/home/suwayomi/.local/share/Tachidesk:Z
    ports:
      - 4568:${SUWAYOMI_PORT}

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: "unless-stopped"
    networks:
      - caddynet
    env_file:
      - .env 
    volumes:
      - ${JELLYFIN_PATH}/config:/config:Z
      - ${JELLYFIN_PATH}/cache:/cache:Z
      - ${MEDIA_PATH}:/media:Z
    ports:
      - 8096:${JELLYFIN_PORT}

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    networks:
      - caddynet
    env_file:
      - .env 
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PORT=${JELLYSEERR_PORT} 
    ports:
      - 5055:${JELLYSEERR_PORT}
    volumes:
      - ${JELLYSEERR_PATH}/config:/app/config:Z
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  radarr:
      image: lscr.io/linuxserver/radarr:latest
      container_name: radarr
      restart: unless-stopped
      networks:
        - caddynet
      environment:
        - TZ=Europe/Paris
      volumes:
        - ${RADARR_PATH}/config:/config:Z
        - ${DATA_PATH}:/data:Z
      ports:
        - 7878:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - caddynet
    environment:
        - TZ=Europe/Paris
    volumes:
      - ${SONARR_PATH}/config:/config:Z
      - ${DATA_PATH}:/data:Z
    ports:
      - 8989:8989

volumes:

networks:
  caddynet:
    attachable: true
    driver: bridge