name: homelab
services:
  caddy:
    container_name: caddy
    image: restartdk/caddy-cloudflare:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env 
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:Z
      - ${CERTIFICATES_PATH}:/data:Z
      - ${CADDY_PATH}/config:/config:Z
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    
  tailscale:
      image: "tailscale/tailscale:latest"
      container_name: tailscale
      hostname: ${TAILSCALE_NAME}
      restart: unless-stopped
      env_file:
        - .env
      cap_add:
        - NET_ADMIN
        - NET_RAW
      environment:
        # location of the state directory of tailscale daemon - needs to be persisted between restarts
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
        - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=${LOCAL_ROUTES}
      volumes:
        # the named volume created in the 'volumes' section below
        - tailscale_data:/var/lib
        - /dev/net/tun:/dev/net/tun
      healthcheck:
        test: ["CMD-SHELL", "tailscale status --peers=false --json | grep -q 'Online.*true'"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
      labels:
        kuma.networking.group.name: "networking"
        kuma.tailscale.docker.parent_name: "networking"
        kuma.tailscale.docker.name: "tailscale"
        kuma.tailscale.docker.docker_container: "tailscale"
        kuma.tailscale.docker.docker_host: 1

  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    env_file:
      - .env 
    volumes:
      - ${GLANCE_PATH}/config:/app/config:Z
      - ${ASSETS_PATH}:/app/assets:Z
    ports:
      - 8080:${GLANCE_PORT}
    environment:
      - GLANCE_PORT=${GLANCE_PORT}
      - GLANCE_SECRET=${GLANCE_SECRET}
      - GLANCE_DANIEL_PASSWORD=${GLANCE_DANIEL_PASSWORD}
      - SERVER_URL=${SERVER_URL}

  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    env_file:
      - .env 
    volumes:
      - ${KOMGA_PATH}/config:/config:Z
      - ${BOOKS_PATH}:/data:Z
    ports:
      - 25600:${KOMGA_PORT}

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: "unless-stopped"
    env_file:
      - .env 
    volumes:
      - ${JELLYFIN_PATH}/config:/config:Z
      - ${JELLYFIN_PATH}/cache:/cache:Z
      - ${MEDIA_PATH}:/media:Z
    ports:
      - 8096:${JELLYFIN_PORT}
    environment:
      - JELLYFIN_PublishedServerUrl=${SERVER_URL}

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    env_file:
      - .env 
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PORT=${JELLYSEERR_PORT} 
    ports:
      - 5055:${JELLYSEERR_PORT}
    volumes:
      - ${JELLYSEERR_PATH}/config:/app/config:Z

volumes:
  tailscale_data:     
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TAILSCALE_DATA_PATH}