global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'srv-nana-node'
    static_configs:
      - targets: ['192.168.200.182:9100']
    scrape_interval: 30s
    metrics_path: /metrics