server:
  proxied: true
  port: ${GLANCE_PORT}
  assets-path: /app/assets
auth:
  secret-key: ${GLANCE_SECRET}
  users:
    daniel:
      password: ${GLANCE_DANIEL_PASSWORD}
theme:
  disable-picker: false
  presets:
    kanso-zen:
      background-color: 210 36 5 
      primary-color: 150 4 78 
      positive-color: 91 13 54 
      negative-color: 353 70 65 
      accent-color: 199 19 62 
    
    kanso-pearl:
      light: true
      background-color: 40 10 94 
      primary-color: 218 14 15 
      positive-color: 86 27 42 
      negative-color: 352 55 52 
      accent-color: 218 34 45 
    
    kanso-mist:
      background-color: 222 13 16 
      primary-color: 150 4 78 
      positive-color: 91 13 54 
      negative-color: 353 70 65 
      accent-color: 199 19 62 
    
    kanso-ink:
      background-color: 220 18 10 
      primary-color: 150 4 78 
      positive-color: 91 13 54 
      negative-color: 353 70 65 
      accent-color: 199 19 62 
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: weather
            location: Madrid, Spain
            units: metric
            hour-format: 24h # alternatively "24h"

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCbRP3c757lWg9M-U7TyEkXA # Theo browne
              - UCcefcZRL2oaA_uBNeo5UOWg # Y combinator
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

      - size: small
        widgets:
          
          - type: custom-api
            title: Tailscale Devices
            title-url: https://login.tailscale.com/admin/machines
            url: https://api.tailscale.com/api/v2/tailnet/-/devices
            headers:
              Authorization: Bearer ${TAILSCALE_API_KEY}
            cache: 10m
            template: |
              {{/* User Variables */}}
              {{/* Set to true if you'd like an indicator for online devices */}}
              {{ $enableOnlineIndicator := true }}

              <style>
                .device-info-container {
                  position: relative;
                  overflow: hidden;
                  height: 1.5em;
                }

                .device-info {
                  display: flex;
                  transition: transform 0.2s ease, opacity 0.2s ease;
                }

                .device-ip {
                  position: absolute;
                  top: 0;
                  left: 0;
                  transform: translateY(-100%);
                  opacity: 0;
                  transition: transform 0.2s ease, opacity 0.2s ease;
                }

                .device-info-container:hover .device-info {
                  transform: translateY(100%);
                  opacity: 0;
                }

                .device-info-container:hover .device-ip {
                  transform: translateY(0);
                  opacity: 1;
                }

                .update-indicator {
                  width: 8px;
                  height: 8px;
                  border-radius: 50%;
                  background-color: var(--color-primary);
                  display: inline-block;
                  margin-left: 4px;
                  vertical-align: middle;
                }

                .offline-indicator {
                  width: 8px;
                  height: 8px;
                  border-radius: 50%;
                  background-color: var(--color-negative);
                  display: inline-block;
                  margin-left: 4px;
                  vertical-align: middle;
                }

                .online-indicator {
                  width: 8px;
                  height: 8px;
                  border-radius: 50%;
                  background-color: var(--color-positive);
                  display: inline-block;
                  margin-left: 4px;
                  vertical-align: middle;
                }

                .device-name-container {
                  display: flex;
                  align-items: center;
                  gap: 8px;
                }

                .indicators-container {
                  display: flex;
                  align-items: center;
                  gap: 4px;
                }
              </style>
              <ul class="list list-gap-10 collapsible-container" data-collapse-after="4">
                {{ range .JSON.Array "devices" }}
                <li>
                  <div class="flex items-center gap-10">
                    <div class="device-name-container grow">
                      <span class="size-h4 block text-truncate color-primary">
                        {{ findMatch "^([^.]+)" (.String "name") }}
                      </span>
                      <div class="indicators-container">
                        {{ if (.Bool "updateAvailable") }}
                        <span class="update-indicator" data-popover-type="text" data-popover-text="Update Available"></span>
                        {{ end }}

                        {{ $lastSeen := .String "lastSeen" | parseTime "rfc3339" }}
                        {{ if not ($lastSeen.After (offsetNow "-10s")) }}
                        {{ $lastSeenTimezoned := $lastSeen.In now.Location }}
                        <span class="offline-indicator" data-popover-type="text"
                          data-popover-text="Offline - Last seen {{ $lastSeenTimezoned.Format " Jan 2 3:04pm" }}"></span>
                        {{ else if $enableOnlineIndicator }}
                          <span class="online-indicator" data-popover-type="text" data-popover-text="Online"></span>
                        {{ end }}
                      </div>
                    </div>
                  </div>
                  <div class="device-info-container">
                    <ul class="list-horizontal-text device-info">
                      <li>{{ .String "os" }}</li>
                      <li>{{ .String "user" }}</li>
                    </ul>
                    <div class="device-ip">
                      {{ .String "addresses.0"}}
                    </div>
                  </div>
                </li>
                {{ end }}
              </ul>

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://media.${DOMAIN}
                icon: /assets/jellyfin.svg
              - title: Jellyseerr
                url: https://media-request.${DOMAIN}
                icon: /assets/jellyseerr.svg
              - title: Komga
                url: https://library.${DOMAIN}
                icon: /assets/komga.svg
              - title: Nextcloud
                url: https://drive.${DOMAIN}
                icon: /assets/nextcloud.svg
              - title: Radarr
                url: https://radarr.${DOMAIN}
                icon: /assets/radarr.svg
              - title: Sonarr
                url: https://sonarr.${DOMAIN}
                icon: /assets/sonarr.svg
              - title: Suwayomi
                url: https://manga.${DOMAIN}
                icon: /assets/suwayomi.svg
              - title: Cockpit
                url: https://admin.${DOMAIN}
                icon: /assets/cockpit.svg
              - title: Prowlarr
                url: https://prowlarr.${DOMAIN}
                icon: /assets/prowlarr.svg